# Libraries

In [1]:
# Import Libraries
import numpy as np
import pandas as pd
import boto3
import re
import paramiko
import threading
import time
import os
from tqdm import tqdm

# Insert credentials and paths

In [2]:
# copy/paste credentials from Learner Lab
credentials = """[default]
aws_access_key_id=ASIAY26HYSAOWRISKDU7
aws_secret_access_key=5ygYbAINNVtoHr3SN6UzoLvFknRzc0PDXqTQ4j5/
aws_session_token=FwoGZXIvYXdzEK///////////wEaDGKRF3EtNZ8QJWPfhyK+AaMaP8g4g6dxhB/hNv8gIb9UzLSl0a//eUzEMGIlIfOp8F1+zmElYZDLSnB+MgsBJOZQLe+dyu79dGQ2Ql8G9l4E4+SF5vv2pTnGCyw3qwGXrw3c55ZeV9KWE93HBxOSIjQi54ISzZF8g2xiadjX2W0rbI9FKYt7sjzk9u5JpV3PtTSmV43p3Jx8ZYINRjqH8XGQwn+nFPDcl+nEHy+M1nQog68PSf7sdMWfdXkznNB42rnOeGZgqWLHmiZjWrIovvqbnQYyLU0MD6EVp6tDPmLEAp3b+/+6neKOkpfyG9xUlfGHkAQDC7/5VO2BUNhnAoUjEg==
"""

In [3]:
# path where your .aws folder is stored on your local machine
local_aws_path = r"C:\Users\Mathis\.aws"

# path where your credentials are stored on your local machine
local_aws_credentials_path = local_aws_path + "\\credentials"

# path where your labsuser key is stored on your local machine
labsuser_path = r"C:\Users\Mathis\Downloads\labsuser.pem"

In [4]:
# update credentials
f = open(local_aws_credentials_path, "w")
f.write(credentials)
f.close()

# Write python files

In [5]:
# write the python file responsible for the addition on the master
with open("master_sqs_add.py", 'w') as f:
    f.write('''\
    
# Import Libraries
import boto3
import sys
import numpy as np
import pandas as pd
import time
import re
import io
import datetime
from tqdm import tqdm
from fnmatch import fnmatch
import os

# Define all our boto3 objects
sqs_client = boto3.client("sqs")
ec2_client = boto3.client("ec2")
ssm_client = boto3.client("ssm")
s3_resource = boto3.resource('s3')

# Create a function that specifies how many rows a SQS Message can contain without exceeding the limit of 256 kB
# INPUT: the size of the input matrices
# OUTPUT: an integer

def define_batch_add(size):
    # number of digits a message can contain for the addition
    max_number = 86000
    
    size_X = size[0]
    size_Y = size[1]
    
    # specify the batch size
    batch_size = max_number // (size_X + size_Y)
    
    # a batch can't exceed the size of the original matrix
    if batch_size > max(list(size)):
        batch_size = max(list(size))

    return batch_size

# Create a function that specifies the number of workers we need and the number of messages we will send to handle the addition 
# based on the batch size of each SQS message and the size of the input matrices
# INPUT: the batch size, the size of the input matrices
# OUTPUT: an integer (number of workers), an integer (number of messages)

def define_number_workers_add(batch_size, size):

    # Maximal number of workers
    number_max = 8
    
    # Initialisation of the message counter
    messages = 0
    
    # Definition of the integer part of the division between our matrix length and the batch size
    ent = size[0]//batch_size
    
    # Definition of the remainder of the division between our matrix length and the batch size
    rest = size[0]%batch_size
    
    # We calculate how many messages we will send
    for i in range(ent):
        messages += 1

    if rest != 0:
        messages += 1
    
    # We determine the number of workers equal to the number of messages if we have less than 8 messages
    if messages < number_max :
        number_of_workers = messages
        
    # If we have more than 8 messages, we will need all our workers
    else:
        number_of_workers = number_max

    if number_of_workers == 0:
        number_of_workers = 1

    return number_of_workers, messages


# Create a function which calculates the cost of our processing based on the AWS pricing, the runtime, the number of workers used
# and the number of messages sent
# INPUT: integer (runtime), integer (number of workers), integer (number of messages)
# OUTPUT: integer (cost in $)

def cost(runtime, number_of_workers, messages):
    
    # We are using t3.micro for each worker, so the price is (0.0104 / 3600) per second
    cost_workers = number_of_workers * (0.0104 / 3600) * runtime
    
    # We are using t3.large for the master, so the price is (0.0832 / 3600) per second
    cost_master = (0.0832 / 3600) * runtime
    
    # We are using 2 standard queues and each message has a size near 256 kB
    # We have to pay 0.09 $ per GB, so the price is (2.44e-04) * 0.09 per message
    cost_queues = 2 * messages * (2.44e-04) * 0.09
    
    # We list all our csv files stored locally and on s3
    directory = "/home/ec2-user/"
    files = os.listdir(directory)
    csv_files = [f for f in files if fnmatch(f,"*.csv")]
    
    # We calculate the cost to store our csv files on s3
    cost_s3 = 0
    for csv in csv_files:
      file_size = os.path.getsize(csv)
      file_size_gb = file_size / (1024 ** 3)
      
      # We have to pay 0.023 $ per GB
      cost_s3 += file_size_gb * 0.023

    final_cost = cost_workers + cost_master + cost_queues + cost_s3

    return final_cost

# Main function which manage the addition on the master
# INPUT: the first dimension of the input matrices, the second dimension of the input matrices
# OUTPUT: None

def master_sqs_add(x,y):
    
    # URL Queues
    request_queue_url = "https://sqs.us-east-1.amazonaws.com/607619944477/request_queue_ec2" 
    response_queue_url = "https://sqs.us-east-1.amazonaws.com/607619944477/response_queue_ec2"
    
    # Creation of random input matrices based on the size specified in the input
    size = (x,y)
    X = np.random.randint(low=0,high=10,size=size)
    Y = np.random.randint(low=0,high=10,size=size)
    
    # Creation of the output matrix
    Z = np.zeros(size)
    
    # We save the input matrices on the EC2 Master as csv
    pd.DataFrame(X).to_csv("/home/ec2-user/X.csv", header=None, index=None)
    pd.DataFrame(Y).to_csv("/home/ec2-user/Y.csv", header=None, index=None)
    
    # We upload the input matrices in the specific S3 Bucket 'cran-matrices-bucket'
    s3_resource.meta.client.upload_file('/home/ec2-user/X.csv', 'cran-matrices-bucket', 'X.csv')
    s3_resource.meta.client.upload_file('/home/ec2-user/Y.csv', 'cran-matrices-bucket', 'Y.csv')
    
    # We define the batch size
    batch_size = define_batch_add(size)
    print("Each message will contain ", batch_size, " rows from X and Y")
    
    # We define the number of workers and the total number of messages
    number_of_workers, messages = define_number_workers_add(batch_size, size)
    print("So, to make the addition between X and Y, we need ", number_of_workers, " workers")
    
    # We start the time
    start = time.time()

    # Getting instance information
    describeInstance = ec2_client.describe_instances()
    
    # We store the id for each worker instance
    InstancesId = []
    for i in describeInstance["Reservations"]:
        for instance in i["Instances"]:
            if instance["State"]["Name"] == "running":
                if re.search("^worker", instance['Tags'][0]["Value"]):
                    InstancesId.append(instance["InstanceId"])
    
    # We are using the SSM Agent to execute linux command from an EC2 to others EC2
    # We execute the necessary python code to process the addition on only the predefined number of workers 
    ssm_command = ssm_client.send_command(InstanceIds=InstancesId[:number_of_workers],DocumentName="AWS-RunShellScript",Parameters={"commands": ["python3 /home/ec2-user/worker_sqs_ssm_add.py"]})
    
    # We define again a message counter to be sure we send then receive each message
    nb_messages = 0
    
    # Definition of the integer part and the remainder of the division between our matrix length and the batch size
    ent = len(X)//batch_size
    rest = len(X)%batch_size
    
    # We display a loading bar with tqdm for sending messages
    with tqdm(total=messages) as pbar:
        pbar.write('Sending Messages: ')
        
        # We send messages to the Request SQS Queue by slicing our input matrices
        # Each message will contain a certain number of rows from X and from Y with their indexes
        for i in range(ent):
            nb_messages += 1
            message = str(X[i*batch_size:(i+1)*batch_size].tolist()) + ';' + str(Y[i*batch_size:(i+1)*batch_size].tolist()) + ';' + str(i*batch_size) + ';' + str((i+1)*batch_size)
            request = sqs_client.send_message(QueueUrl=request_queue_url,MessageBody=message)
            
            # We update the loading bar
            pbar.update(1)
            time.sleep(0.01)
        
        # If the remainder is not null, we need also to send the final part of our input matrices
        if rest != 0:
            nb_messages += 1
            message_final = str(X[ent*batch_size:].tolist()) + ';' + str(Y[ent*batch_size:].tolist()) + ';' + str(ent*batch_size) + ';' + str(len(X))
            request = sqs_client.send_message(QueueUrl=request_queue_url,MessageBody=message_final)
            
            # We update the loading bar
            pbar.update(1)
            time.sleep(0.01)
    
    print('Total number of message send: ', nb_messages)
    
    # We display a loading bar with tqdm for receiving messages
    with tqdm(total=messages) as pbar:
        pbar.write('Receiving Messages: ')
        
        # We are waiting to receive each message we sent
        while nb_messages > 0:
            
            # We retrieve each message of the Response SQS Queue
            response = sqs_client.receive_message(QueueUrl=response_queue_url)
            
            for message in response.get("Messages", []):
                
                # For each message we receive, we decrease our counter by 1
                nb_messages -= 1
                
                data = message["Body"]
                receipt_handle = message['ReceiptHandle']
                
                # We process our message
                data = data.split(';')
                
                result = np.array([float(i) for i in re.findall('[-+]?\d+\.?\d*', data[0])])
                
                index_0 = int(re.findall('[-+]?\d+\.?\d*', str(data[1]))[0])

                index_1 = int(re.findall('[-+]?\d+\.?\d*', str(data[2]))[0])

                result = result.reshape(index_1-index_0,len(X[0]))
                
                # We correctly place our rows of matrix resulting from the addition
                Z[index_0:index_1] += result
                
                # After processing our message, we delete it from the queue
                delete = sqs_client.delete_message(QueueUrl=response_queue_url, ReceiptHandle=receipt_handle)

                pbar.update(1)
                time.sleep(0.01)
    
    # We calculate the time it takes to make the addition between our two input matrices
    end = time.time()
    runtime = end-start
    runtime = round(runtime, 2)
    print("It takes ",runtime,"sec to calculate the addition of the two matrices")
    
    # We store our output matrix as csv on the EC2 Master and also on the S3 Bucket 'cran-matrices-bucket'
    pd.DataFrame(Z).to_csv("/home/ec2-user/Z.csv", header=None, index=None)
    s3_resource.meta.client.upload_file('/home/ec2-user/Z.csv', 'cran-matrices-bucket', 'Z.csv')
    
    # We estimate the cost of this operation
    final_cost = cost(runtime, number_of_workers, messages)
    print("It costs ",final_cost,"$ to calculate the addition of the two matrices")
    
    # We close the SSM Command we executed before on each worker
    command_id = ssm_command['Command']['CommandId']
    response = ssm_client.cancel_command(CommandId=command_id, InstanceIds=InstancesId)

if __name__ == '__main__':
    # Arguments:
    #   the first dimension of the input matrices
    #   the second dimension of the input matrices
    master_sqs_add(int(sys.argv[1]),int(sys.argv[2]))        
''')
    f.close()

In [6]:
# write the python file responsible for the multiplication on the master
with open("master_sqs_mult.py", 'w') as f:
    f.write('''\

# Import Libraries
import boto3
import sys
import numpy as np
import pandas as pd
import time
import re
import io
import datetime
from tqdm import tqdm
from fnmatch import fnmatch
import os

# Define all our boto3 objects
sqs_client = boto3.client("sqs", region_name='us-east-1')
ec2_client = boto3.client("ec2")
ssm_client = boto3.client("ssm")
s3_resource = boto3.resource('s3')

# Create a function that specifies how many rows a SQS Message can contain without exceeding the limit of 256 kB
# INPUT: the size of the input matrix X, the size of the input matrix Y
# OUTPUT: an integer (batch size for X), an integer (batch size for Y)

def define_batch_mult(X_size, Y_size):

    # number of digits a message can contain for the multiplication
    max_number = 43000
    
    # specify the batch size for X
    batch_size_X = max_number // X_size[0]
    
    # specify the batch size for Y
    batch_size_Y = max_number // Y_size[1]
    
    # a batch can't exceed the size of the original matrix
    if batch_size_X > X_size[0]:
        batch_size_X = X_size[0]
    
    # a batch can't exceed the size of the original matrix
    if batch_size_Y > Y_size[1]:
        batch_size_Y = Y_size[1]

    return batch_size_X, batch_size_Y

# Create a function that specifies the number of workers we need and the number of messages we will send to handle the multiplication 
# based on the batch size of each SQS message for X and Y and the size of the input matrices
# INPUT: the batch size for X, the batch size for Y, the size of X, the size of Y
# OUTPUT: an integer (number of workers), an integer (number of messages)

def define_number_workers_mult(batch_size_X, batch_size_Y, X, Y):
    
    # Maximal number of workers
    number_max = 8
    
    # Initialisation of the message counter
    messages = 0
    
    # Definition of the integer part and the remainder of the division between X length and X batch size
    ent_X = len(X)//batch_size_X
    rest_X = len(X)%batch_size_X
    
    # Definition of the integer part and the remainder of the division between Y length and Y batch size
    ent_Y = len(Y[0])//batch_size_Y
    rest_Y = len(Y[0])%batch_size_Y
    
    # We calculate how many messages we will send
    for i in range(ent_X):
        for j in range(ent_Y):
            messages += 1
        if rest_Y != 0:
            messages += 1
    
    if rest_X != 0:
        for j in range(ent_Y):
            messages += 1
        if rest_Y != 0:
            messages += 1
    
    # We determine the number of workers equal to the number of messages if we have less than 8 messages
    if messages < number_max :
        number_of_workers = messages
    
    # If we have more than 8 messages, we will need all our workers
    else:
        number_of_workers = number_max

    if number_of_workers == 0:
        number_of_workers = 1

    return number_of_workers, messages

# Create a function which calculates the cost of our processing based on the AWS pricing, the runtime, the number of workers used
# and the number of messages sent
# INPUT: integer (runtime), integer (number of workers), integer (number of messages)
# OUTPUT: integer (cost in $)

def cost(runtime, number_of_workers, messages):
    
    # We are using t3.micro for each worker, so the price is (0.0104 / 3600) per second
    cost_workers = number_of_workers * (0.0104 / 3600) * runtime
    
    # We are using t3.large for the master, so the price is (0.0832 / 3600) per second
    cost_master = (0.0832 / 3600) * runtime
    
    # We are using 2 standard queues and each message has a size near 256 kB
    # We have to pay 0.09 $ per GB, so the price is (2.44e-04) * 0.09 per message
    cost_queues = 2 * messages * (2.44e-04) * 0.09
    
    # We list all our csv files stored locally and on s3
    directory = "/home/ec2-user/"
    files = os.listdir(directory)
    csv_files = [f for f in files if fnmatch(f,"*.csv")]
    
    # We calculate the cost to store our csv files on s3
    cost_s3 = 0
    for csv in csv_files:
      file_size = os.path.getsize(csv)
      file_size_gb = file_size / (1024 ** 3)
      
      # We have to pay 0.023 $ per GB
      cost_s3 += file_size_gb * 0.023

    final_cost = cost_workers + cost_master + cost_queues

    return final_cost

# Main function which manage the multiplication on the master
# INPUT: the first dimension of X, the second dimension of X, the first dimension of Y, the second dimension of Y
# OUTPUT: None

def master_sqs_mult(x_0, x_1, y_0, y_1):
    
    # URL Queues
    request_queue_url = "https://sqs.us-east-1.amazonaws.com/607619944477/request_queue_ec2" 
    response_queue_url = "https://sqs.us-east-1.amazonaws.com/607619944477/response_queue_ec2"
    
    # Creation of random input matrices based on the size specified in the input
    X_size = (x_0,x_1)
    Y_size = (y_0,y_1)
    X = np.random.randint(low=0,high=10,size=X_size)
    Y = np.random.randint(low=0,high=10,size=Y_size)
    
    # Creation of the output matrix
    Z = np.zeros((x_0,y_1))
    
    # We save the input matrices on the EC2 Master as csv
    pd.DataFrame(X).to_csv("/home/ec2-user/X.csv", header=None, index=None)
    pd.DataFrame(Y).to_csv("/home/ec2-user/Y.csv", header=None, index=None)
    
    # We upload the input matrices in the specific S3 Bucket 'cran-matrices-bucket'
    s3_resource.meta.client.upload_file('/home/ec2-user/X.csv', 'cran-matrices-bucket', 'X.csv')
    s3_resource.meta.client.upload_file('/home/ec2-user/Y.csv', 'cran-matrices-bucket', 'Y.csv')
    
    # We define the batch size
    batch_size_X, batch_size_Y = define_batch_mult(X_size, Y_size)
    print("Each message will contain ", batch_size_X, " rows from X and ", batch_size_Y, " columns from Y")
    
    # We define the number of workers and the total number of messages
    number_of_workers, messages = define_number_workers_mult(batch_size_X, batch_size_Y, X, Y)
    print("So, to make the addition between X and Y, we need ", number_of_workers, " workers")
    
    # We start the time
    start = time.time()

    # Getting instance information
    describeInstance = ec2_client.describe_instances()
    
    # We store the id for each worker instance
    InstancesId = []
    for i in describeInstance["Reservations"]:
        for instance in i["Instances"]:
            if instance["State"]["Name"] == "running":
                if re.search("^worker", instance['Tags'][0]["Value"]):
                    InstancesId.append(instance["InstanceId"])
    
    # We are using the SSM Agent to execute linux command from an EC2 to others EC2
    # We execute the necessary python code to process the addition on only the predefined number of workers 
    ssm_command = ssm_client.send_command(InstanceIds=InstancesId[:number_of_workers],DocumentName="AWS-RunShellScript",Parameters={"commands": ["python3 /home/ec2-user/worker_sqs_ssm_mult.py"]})
    
    # We define again a message counter to be sure we send then receive each message
    nb_messages = 0
    
    # Definition of the integer part and the remainder of the division between X length and the batch size for X
    ent_X = len(X)//batch_size_X
    rest_X = len(X)%batch_size_X
    
    # Definition of the integer part and the remainder of the division between Y length and the batch size for Y
    ent_Y = len(Y[0])//batch_size_Y
    rest_Y = len(Y[0])%batch_size_Y
    
    # We display a loading bar with tqdm for sending messages
    with tqdm(total=messages) as pbar:
        pbar.write('Sending Messages: ')
        
        # We send messages to the Request SQS Queue by slicing our input matrices
        # Each message will contain a certain number of rows from X and from Y with their indexes
        for i in range(ent_X):
            for j in range(ent_Y):
                nb_messages += 1
                message = str(X[i*batch_size_X:(i+1)*batch_size_X].tolist()) + ';' + str(Y[:, j*batch_size_Y:(j+1)*batch_size_Y].tolist()) + ';' + str(i*batch_size_X) + ';' + str((i+1)*batch_size_X) + ';' + str(j*batch_size_Y)+ ';' + str((j+1)*batch_size_Y)
                request = sqs_client.send_message(QueueUrl=request_queue_url,MessageBody=message)
                
                # We update the loading bar
                pbar.update(1)
                time.sleep(0.01)

            if rest_Y != 0:
                nb_messages += 1
                message = str(X[i*batch_size_X:(i+1)*batch_size_X].tolist()) + ';' + str(Y[:,ent_Y*batch_size_Y:].tolist()) + ';' + str(i*batch_size_X) + ';' + str((i+1)*batch_size_X) + ';' + str(ent_Y*batch_size_Y) + ';' + str(len(Y[0]))
                request = sqs_client.send_message(QueueUrl=request_queue_url,MessageBody=message)
                
                # We update the loading bar
                pbar.update(1)
                time.sleep(0.01)

        if rest_X != 0:
            for j in range(ent_Y):
                nb_messages += 1
                message = str(X[ent_X*batch_size_X:].tolist()) + ';' + str(Y[:, j*batch_size_Y:(j+1)*batch_size_Y].tolist()) + ';' + str(ent_X*batch_size_X) + ';' + str(len(X)) + ';' + str(j*batch_size_Y)+ ';' + str((j+1)*batch_size_Y)
                request = sqs_client.send_message(QueueUrl=request_queue_url,MessageBody=message)
                
                # We update the loading bar
                pbar.update(1)
                time.sleep(0.01)   
        
            if rest_Y != 0:
                nb_messages += 1
                message_final = str(X[ent_X*batch_size_X:].tolist()) + ';' + str(Y[:,ent_Y*batch_size_Y:].tolist()) + ';' + str(ent_X*batch_size_X) + ';' + str(len(X)) + ';' + str(ent_Y*batch_size_Y) + ';' + str(len(Y[0]))
                request = sqs_client.send_message(QueueUrl=request_queue_url,MessageBody=message_final)
                
                # We update the loading bar
                pbar.update(1)
                time.sleep(0.01)
    
    print('Total number of message send: ', nb_messages)
    
    # We display a loading bar with tqdm for receiving messages
    with tqdm(total=messages) as pbar:
        pbar.write('Receiving Messages: ')
        
        # We are waiting to receive each message we sent
        while nb_messages > 0:
            
            # We retrieve each message of the Response SQS Queue
            response = sqs_client.receive_message(QueueUrl=response_queue_url)

            for message in response.get("Messages", []):
                
                # For each message we receive, we decrease our counter by 1
                nb_messages -= 1
                
                data = message["Body"]
                receipt_handle = message['ReceiptHandle']

                # We process our message
                data = data.split(';')
                
                result = np.array([float(i) for i in re.findall('[-+]?\d+\.?\d*', str(data[0]))])
                
                X_index_0 = int(re.findall('[-+]?\d+\.?\d*', str(data[1]))[0])
                X_index_1 = int(re.findall('[-+]?\d+\.?\d*', str(data[2]))[0])
                Y_index_0 = int(re.findall('[-+]?\d+\.?\d*', str(data[3]))[0])
                Y_index_1 = int(re.findall('[-+]?\d+\.?\d*', str(data[4]))[0])

                result = result.reshape(X_index_1-X_index_0,Y_index_1-Y_index_0)
                
                # We correctly place our rows of matrix resulting from the multiplication
                Z[X_index_0:X_index_1,Y_index_0:Y_index_1] = result
                
                # After processing our message, we delete it from the queue
                delete = sqs_client.delete_message(QueueUrl=response_queue_url, ReceiptHandle=receipt_handle)
                
                # We update the loading bar
                pbar.update(1)
                time.sleep(0.01)
    
    # We calculate the time it takes to make the addition between our two input matrices
    end = time.time()
    runtime = end-start
    runtime = round(runtime, 2)
    print("It takes ",runtime,"sec to calculate the multiplication of the two matrices")
    
    # We store our output matrix as csv on the EC2 Master and also on the S3 Bucket 'cran-matrices-bucket'
    pd.DataFrame(Z).to_csv("/home/ec2-user/Z.csv", header=None, index=None)
    s3_resource.meta.client.upload_file('/home/ec2-user/Z.csv', 'cran-matrices-bucket', 'Z.csv')
    
    # We estimate the cost of this operation
    final_cost = cost(runtime, number_of_workers, messages)
    print("It costs ",final_cost,"$ to calculate the multiplication of the two matrices")
    
    # We close the SSM Command we executed before on each worker
    command_id = ssm_command['Command']['CommandId']
    response = ssm_client.cancel_command(CommandId=command_id, InstanceIds=InstancesId)

if __name__ == '__main__':
    # Arguments:
    #   the first dimension of the input matrix X
    #   the second dimension of the input matrix X
    #   the first dimension of the input matrix Y
    #   the second dimension of the input matrix Y
    master_sqs_mult(int(sys.argv[1]),int(sys.argv[2]),int(sys.argv[3]),int(sys.argv[4]))
''')
    f.close

In [7]:
# write the python file responsible for the addition on the workers
with open("worker_sqs_ssm_add.py", 'w') as f:
    f.write('''\
# Import Libraries
import boto3
import sys
import numpy as np
import re
import time

# Main function which manage the addition on the worker
# INPUT: None
# OUTPUT: None
def worker_sqs_add():
    
    # URL Queues
    request_queue_url = "https://sqs.us-east-1.amazonaws.com/607619944477/request_queue_ec2" 
    response_queue_url = "https://sqs.us-east-1.amazonaws.com/607619944477/response_queue_ec2"

    # Create SQS client
    sqs_client = boto3.client("sqs", region_name='us-east-1') 
    
    # Our workers will search for any messages in the SQS Request Queue until we stopped them
    while True:
        
        # We retrieve each message of the Request SQS Queue
        response = sqs_client.receive_message(QueueUrl=request_queue_url)
        
        # We process our message
        for message in response.get("Messages", []):
            
            data = message["Body"]
            receipt_handle = message['ReceiptHandle']

            data = data.split(';')
            
            # We make the addition
            add = np.array([float(i) for i in re.findall('[-+]?\d+\.?\d*', data[0])]) + np.array([float(i) for i in re.findall('[-+]?\d+\.?\d*', data[1])])
            
            # We create our message composed of the result of the addition and the indexes
            result = str(add.tolist()) + ';' + data[2] + ';' + data[3]
            
            # We send the message in the SQS Response Queue
            response = sqs_client.send_message(QueueUrl=response_queue_url,MessageBody=result)
            
            # We delete the message we just processed
            delete = sqs_client.delete_message(QueueUrl=request_queue_url, ReceiptHandle=receipt_handle)

if __name__ == '__main__':
    worker_sqs_add()  
''')
    f.close

In [8]:
# write the python file responsible for the multiplication on the workers
with open("worker_sqs_ssm_mult.py", 'w') as f:
    f.write('''\
# Import Libraries
import boto3
import sys
import numpy as np
import re
import time

# Main function which manage the multiplication on the worker
# INPUT: None
# OUTPUT: None    
def worker_sqs_mult():
    
    # URL Queues
    request_queue_url = "https://sqs.us-east-1.amazonaws.com/607619944477/request_queue_ec2" 
    response_queue_url = "https://sqs.us-east-1.amazonaws.com/607619944477/response_queue_ec2"

    # Create SQS client
    sqs_client = boto3.client("sqs", region_name='us-east-1')
    
    # Our workers will search for any messages in the SQS Request Queue until we stopped them
    while True:
        
        # We retrieve each message of the Request SQS Queue
        response = sqs_client.receive_message(QueueUrl=request_queue_url)
        
        # We process our message
        for message in response.get("Messages", []):
            
            data = message["Body"]
            receipt_handle = message['ReceiptHandle']

            data = data.split(';')
            
            # We make the multiplication
            mult = np.array([float(i) for i in re.findall('[-+]?\d+\.?\d*', data[0])]).reshape(int(data[3])-int(data[2]),-1) @ np.array([float(i) for i in re.findall('[-+]?\d+\.?\d*', data[1])]).reshape(-1,int(data[5])-int(data[4]))
            
            # We create our message composed of the result of the addition and the indexes
            result = str(mult.tolist()) + ';' + data[2] + ';' + data[3] + ';' + data[4] + ';' + data[5]
            
            # We send the message in the SQS Response Queue
            response = sqs_client.send_message(QueueUrl=response_queue_url,MessageBody=result)
            
            # We delete the message we just processed
            delete = sqs_client.delete_message(QueueUrl=request_queue_url, ReceiptHandle=receipt_handle)

if __name__ == '__main__':
    worker_sqs_mult()
''')
    f.close

# Functions

## Create Cloud Environment

In [9]:
# Function that creates security group for our ec2 instances by allowing everything
# INPUT: None
# OUTPUT: None
def create_ec2_security_group():
    
    # EC2 Client
    ec2 = boto3.client('ec2')
    
    # Get our VPC ID
    response = ec2.describe_vpcs()
    vpc_id = response.get('Vpcs', [{}])[0].get('VpcId', '')
    
    # Create our Security Group
    response = ec2.create_security_group(GroupName='ec2_security_group',
                                         Description='ec2_security_group',
                                         VpcId=vpc_id)
    security_group_id = response['GroupId']
    print('Security Group Created %s in vpc %s.' % (security_group_id, vpc_id))
    
    # Allow everything
    data = ec2.authorize_security_group_ingress(
        GroupId=security_group_id,
        IpPermissions=[
            {'IpProtocol': 'tcp',
             'FromPort': 80,
             'ToPort': 80,
             'IpRanges': [{'CidrIp': '0.0.0.0/0'}]},
            {'IpProtocol': 'tcp',
             'FromPort': 22,
             'ToPort': 22,
             'IpRanges': [{'CidrIp': '0.0.0.0/0'}]},
            {'IpProtocol': 'tcp',
             'FromPort': 443,
             'ToPort': 443,
             'IpRanges': [{'CidrIp': '0.0.0.0/0'}]}
        ])

In [10]:
# Function that creates our ec2 master from a certain type
# The EC2 Master will be pre-configured
# INPUT: instance type (string), local aws path (string), labsuser.pem path (string)
# OUTPUT: None
def create_ec2_master(instance_type, local_aws_path, labsuser_path):

    # boto3 client/ressource
    ec2 = boto3.resource('ec2')
    client = boto3.client("ec2")
    ssm = boto3.client("ssm")
    
    # Getting security group information
    response = client.describe_security_groups()
    
    # Get security group id
    for sg in response['SecurityGroups']:
        if re.search("^ec2", sg['GroupName']): 
            security_group_id = sg['GroupId']

    Instances = []
    InstancesId = []
    
    # Create EC2 Master
    instance = ec2.create_instances(
        ImageId="ami-0b0dcb5067f052a63",
        MinCount=1,
        MaxCount=1,
        InstanceType=instance_type,
        KeyName="vockey",
        SecurityGroupIds=[security_group_id],
        IamInstanceProfile={
            'Arn': 'arn:aws:iam::607619944477:instance-profile/LabInstanceProfile'
        },
        TagSpecifications=[
            {
                'ResourceType': 'instance',
                'Tags': 
                [
                    {
                        'Key': 'Name',
                        'Value': 'master_aws_linux_' + instance_type.replace('.','_')
                    },
                ]
            }
        ]
    )

    
    master_ec2 = instance[0]
    print('Master Instance Id: ', master_ec2.id)
    InstancesId.append(master_ec2.id)
    time.sleep(3)
    
    # Start the EC2 Master
    print('Start Master')
    master_ec2.start()
    
    # Waiting the EC2 Master to run
    if master_ec2.state["Name"] != "running":
        master_ec2.wait_until_running()
    
    master_ec2.reload()
    print('Master is running !')
    time.sleep(3)
    print('Send aws folder & python files')
    
    filepath = os.getcwd()
    add_file = 'master_sqs_add.py'
    mult_file = 'master_sqs_mult.py'
    
    temp_add_path = filepath + '\\' + add_file
    temp_mult_path = filepath + '\\' + mult_file
    
    # We send the .aws folder with the credentials and 2 python files
    os.system(r'scp -o StrictHostKeyChecking=no -i ' + labsuser_path + ' -r ' + local_aws_path + ' ec2-user@' + master_ec2.public_ip_address + r':~\ ')    
    os.system(r'scp -o StrictHostKeyChecking=no -i ' + labsuser_path + ' ' + temp_add_path + ' ec2-user@' + master_ec2.public_ip_address + r':~\ ')
    os.system(r'scp -o StrictHostKeyChecking=no -i ' + labsuser_path + ' ' + temp_mult_path + ' ec2-user@' + master_ec2.public_ip_address + r':~\ ')
    
    master_ec2.reload()
    time.sleep(3)
    print('Install packages')
    
    # We install packages on our EC2 Master via SSM Agent
    ssm_command = ssm.send_command(InstanceIds=[master_ec2.id],DocumentName="AWS-RunShellScript",Parameters={"commands": ["pip3 install boto3", "pip3 install numpy", "pip3 install pandas", "pip3 install paramiko", "pip3 install thread6", "pip3 install tqdm"]})
    print('Done !')

In [11]:
# Function that creates a certain number of ec2 workers
# The EC2 Workers will be pre-configured
# INPUT: number of workers (integer), local aws path (string), labsuser.pem path (string)
# OUTPUT: None
def create_ec2_workers(nb_workers, local_aws_path, labsuser_path):

    # boto3 client/ressource
    ec2 = boto3.resource('ec2')
    client = boto3.client("ec2")
    ssm = boto3.client("ssm")
    
    # Getting security group information
    response = client.describe_security_groups()
    
    # Get security group id
    for sg in response['SecurityGroups']:
        if re.search("^ec2", sg['GroupName']): 
            security_group_id = sg['GroupId']

    Instances = []
    InstancesId = []
    
    # Create the number of workers specified
    for i in range(1, nb_workers+1):
        instance = ec2.create_instances(
                ImageId="ami-0b0dcb5067f052a63",
                MinCount=1,
                MaxCount=1,
                InstanceType="t3.micro",
                KeyName="vockey",
                SecurityGroupIds=[security_group_id],
                IamInstanceProfile={
                    'Arn': 'arn:aws:iam::607619944477:instance-profile/LabInstanceProfile'
                },
                TagSpecifications=[
                    {
                        'ResourceType': 'instance',
                        'Tags': 
                        [
                            {
                                'Key': 'Name',
                                'Value': 'worker_aws_linux_' + str(i)
                            },
                        ]
                    }
                ]
        )

        Instances.append(instance[0])
        InstancesId.append(instance[0].id)
        print("Starting instance " + instance[0].id)
        time.sleep(3)
        
        # Start the EC2 Worker
        instance[0].start()
    
    # Waiting all our EC2 Workers to run
    while True:
        response = client.describe_instance_status(InstanceIds=InstancesId, IncludeAllInstances=True)
        state = response['InstanceStatuses'][0]['InstanceState']

        # If status is 16 ('running'), then proceed, else, wait 5 seconds and try again
        if state['Code'] == 16:
            break
        else:
            time.sleep(5)
    
    print('Every workers are running !')
    
    filepath = os.getcwd()
    add_file = 'worker_sqs_ssm_add.py'
    mult_file = 'worker_sqs_ssm_mult.py'
    
    temp_add_path = filepath + '\\' + add_file
    temp_mult_path = filepath + '\\' + mult_file
    
    # Looping through instance ids
    for instance in Instances:
        print('Instance: ', instance)
        instance.reload()
        
        # To be sure, our worker is running
        if instance.state["Name"] != "running":
            instance.wait_until_running()

        instance.reload()
        time.sleep(3)
        
        print('Send aws folder & python files')
        
        # We send the .aws folder with the credentials and 2 python files
        os.system(r'scp -o StrictHostKeyChecking=no -i ' + labsuser_path + ' -r ' + local_aws_path + ' ec2-user@' + instance.public_ip_address + r':~\ ')
        os.system(r'scp -o StrictHostKeyChecking=no -i ' + labsuser_path + ' ' + temp_add_path + ' ec2-user@' + instance.public_ip_address + r':~\ ')
        os.system(r'scp -o StrictHostKeyChecking=no -i ' + labsuser_path + ' ' + temp_mult_path + ' ec2-user@' + instance.public_ip_address + r':~\ ')
        instance.reload()
    
    time.sleep(3)
    print('Install packages')
    
    # We install packages on our EC2 Worker via SSM Agent
    ssm_command = ssm.send_command(InstanceIds=InstancesId,DocumentName="AWS-RunShellScript",Parameters={"commands": ["pip3 install boto3", "pip3 install numpy", "pip3 install pandas", "pip3 install paramiko", "pip3 install thread6", "pip3 install tqdm"]})
    print('Done !')

In [12]:
# Function that creates a S3 Bucket
# INPUT: name of the bucket (string)
# OUTPUT: None
def create_s3_bucket(bucket_name):
    
    # boto3 ressource
    s3 = boto3.resource('s3')
    
    s3.create_bucket(Bucket=bucket_name)
    print('Bucket S3 created !')

In [13]:
# Function that creates a SQS Queue
# INPUT: name of the queue (string)
# OUTPUT: None
def create_sqs_queue(queue_name):
    
    # boto3 client
    sqs_client = boto3.client("sqs")
    
    response = sqs_client.create_queue(QueueName=queue_name)
    print('SQS Queue ', queue_name, ' created !')

In [14]:
# Function that creates our Cloud environment
# INPUT: local aws path (string), labsuser.pem path (string), master instance type (string), number of workers (integer), name of the bucket (string), name of the request queue (string), name of the response queue (string)
# OUTPUT: None
def create_cloud_env(local_aws_path, labsuser_path, master_type, nb_workers, bucket_name, request_queue_name, response_queue_name):
    
    # We display a loading bar with tqdm to monitor the progress of the deployement
    with tqdm(total=6) as pbar:
        
        # Create the secrurity group
        create_ec2_security_group()
        # We update the loading bar
        time.sleep(1)
        pbar.update(1)
        
        # Create the EC2 Master
        create_ec2_master(master_type, local_aws_path, labsuser_path)
        # We update the loading bar
        time.sleep(1)
        pbar.update(1)
        
        # Create the EC2 Workers
        create_ec2_workers(nb_workers, local_aws_path, labsuser_path)
        # We update the loading bar
        time.sleep(1)
        pbar.update(1)
        
        # Create the S3 Bucket
        create_s3_bucket(bucket_name)
        # We update the loading bar
        time.sleep(1)
        pbar.update(1)
        
        # Create the SQS Request Queue
        create_sqs_queue(request_queue_name)
        # We update the loading bar
        time.sleep(1)
        pbar.update(1)
        
        # Create the SQS Response Queue
        create_sqs_queue(response_queue_name)
        # We update the loading bar
        time.sleep(1)
        pbar.update(1)
        

## Calculations

In [15]:
# a function group that asks the user to choose between performing an addition or a multiplication
# and checks that the user's input is correct

# First function asks to choose between performing an addition or a multiplication
def ask_operation_0():
    print("If you want to make an addition, please type 0")
    print("Or if you want to make a multiplication, please type 1")
    input_user = input('Choose: ')
    return input_user

# Second function is checking if the user's input is an integer
# and if not, calling again the first function
def ask_operation_1():
    
    # Calling the first function
    input_user = ask_operation_0()
    
    # While loop to check if the user's input is an integer with regex
    while not re.match(r'^[0-9]*$',input_user):
        print('The type of your input is not correct, you have to write either 0 or 1!\n')
        input_user = ask_operation_0()

    return input_user

# Third function is checking if the user's input is either 0 or 1
# and if not, calling again the second function
def ask_operation_2():
    
    # Calling the second function
    input_user = ask_operation_1()
    
    # While loop to check if the user's input is either 0 or 1
    while True:
        if input_user == '0' or input_user == '1':
            break
        else:
            print('The value of your input is not correct, you have to write either 0 or 1!\n')
            input_user = ask_operation_1()
        
    return input_user

In [16]:
# a function group that asks the user to enter a matrix shape for performing an addition
# and checks that the user's input is correct

# First function asks to enter a matrix shape for performing an addition
def ask_shape_add_matrix_0():
    input_user = input('Enter matrix shape (like "10 10" for (10,10) matrix): ')
    return input_user

# Second function is checking if the user's input is a whape with integers
# and if not, calling again the first function
def ask_shape_add_matrix_1():
    
    # Calling the first function
    input_user = ask_shape_add_matrix_0()
    
    size_list = input_user.split()
    
    # Allocating dimensions
    size_x = size_list[0]
    size_y = size_list[1]
    
    # While loop to check if the user's input first dimension is an integer with regex
    while not re.match(r'^[0-9]*$',size_x):
        print('The type of your input is not correct, you have to write an integer for the first dimension!\n')
        
        input_user = ask_shape_add_matrix_0()
        size_list = input_user.split()
        size_x = size_list[0]
        size_y = size_list[1]
    
    # While loop to check if the user's input second dimension is an integer with regex
    while not re.match(r'^[0-9]*$',size_y):
        print('The type of your input is not correct, you have to write an integer for the second dimension!\n')
        
        input_user = ask_shape_add_matrix_0()
        size_list = input_user.split()
        size_x = size_list[0]
        size_y = size_list[1]
    
    # Assigning dimensions
    size_x = int(float(size_list[0]))
    size_y = int(float(size_list[1]))
    
    return size_x, size_y

# Third function is checking if the matrix shape is between (0,0) and (18000,18000)
# and if not, calling again the second function
def ask_shape_add_matrix_2():
    
    # Calling the second function
    size_x, size_y = ask_shape_add_matrix_1()
    
    # While loop to check if the matrix shape is between (0,0) and (18000,18000)
    while True:
        if (size_x > 0 and size_y > 0) and (size_x < 18000 or size_y < 18000):
            break
        else:
            print('The value of your input is not correct, you have to write either a shape between (1,1) and (18000, 18000)!\n')
            size_x, size_y = ask_shape_add_matrix_1()
        
    return size_x, size_y

In [17]:
# a function group that asks the user to enter a matrix shape for performing an multiplication
# and checks that the user's input is correct

# First function asks to enter 2 matrix shapes for performing an multiplication 
# using our previous function 'ask_shape_add_matrix_2()'
def ask_shape_mult_matrix_0():
    X_size = ask_shape_add_matrix_2()
    Y_size = ask_shape_add_matrix_2()
    
    return X_size, Y_size

# Second function is checking if the second dimension of the first matrix is equal to the first dimension of the second matrix
# and if not, calling again the first function
def ask_shape_mult_matrix_1():
    
    # Calling the first function
    X_size, Y_size = ask_shape_mult_matrix_0()
    
    # Checking the equality
    if X_size[1] == Y_size[0]:
        print("We can calculate matrix multiplication for this shapes of matrices !")

    else:
        while(X_size[1] != Y_size[0]):
            print("To calculate matrix multiplication, change the shapes of matrices !")
            X_size, Y_size = ask_shape_mult_matrix_0()

    return X_size, Y_size

In [18]:
# Function that remotly runs the 'master_sqs_add.py' file on the EC2 Master
# INPUT: labsuser.pem path (string), ip address from the EC2 Master (string), first dimension of the input matrices (integer), second dimension of the input matrices (integer), a timeout (integer)
# OUTPUT: None
def run_addition(labsuser_path, ip, size_x, size_y, timeout):
    
    # paramiko parameters
    ssh_username = "ec2-user"
    key = paramiko.RSAKey.from_private_key_file(labsuser_path)
    
    # Create SSH Client with paramiko
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    
    # Connect to our EC2 Master via SSH
    ssh.connect(hostname=ip, username=ssh_username, pkey=key)
    
    # Write the linux command we want to execute on the EC2 Master
    command = "python3 master_sqs_add.py " + str(size_x) + " " + str(size_y) + " " + str(timeout)
    
    # Execute the command
    stdin, stdout, stderr = ssh.exec_command(command, get_pty=True)
    
    # Print in real time the output with a channel
    channel = stdout.channel
    while True:
        s = channel.recv(2048).decode('utf8')
        if s == '':
            break
        else:
            print(s)
            
    # Close the SSH connection
    ssh.close()

In [19]:
# Function that remotly runs the 'master_sqs_mult.py' file on the EC2 Master
# INPUT: labsuser.pem path (string), ip address from the EC2 Master (string), first and second dimension of X (integers), first and second dimension of Y (integers), a timeout (integer)
# OUTPUT: None
def run_multiplication(labsuser_path, ip, x_0, x_1, y_0, y_1, timeout):
    
    # paramiko parameters
    ssh_username = "ec2-user"
    key = paramiko.RSAKey.from_private_key_file(labsuser_path)
    
    # Create SSH Client with paramiko
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    
    # Connect to our EC2 Master via SSH
    ssh.connect(hostname=ip, username=ssh_username, pkey=key)
    
    # Write the linux command we want to execute on the EC2 Master
    command = "python3 master_sqs_mult.py " + str(x_0) + " " + str(x_1) + " " + str(y_0) + " " + str(y_1) + " " + str(timeout)
    
    # Execute the command
    stdin, stdout, stderr = ssh.exec_command(command, get_pty=True)
    
    # Print in real time the output with a channel
    channel = stdout.channel
    while True:
        s = channel.recv(2048).decode('utf8')
        if s == '':
            break
        else:
            print(s)
    
    # Close the SSH connection
    ssh.close()

In [20]:
# Function that retrieves a csv file from a s3 bucket and transforms it into a numpy array
# INPUT: bucket name (string), a csv file name (string)
# OUTPUT: a numpy array
def get_csv(bucket, file_name):
    
    # boto3 client
    s3_client = boto3.client('s3')
    
    # Get object and file (key) from a s3 bucket
    obj = s3_client.get_object(Bucket=bucket, Key=file_name) 
    
    # Read our object into a pandas
    matrice_df = pd.read_csv(obj['Body'], sep=',', header=None)
    
    # Convert our pandas to a numpy
    matrice_numpy = matrice_df.to_numpy()
    
    return matrice_numpy

In [21]:
# a function group that verifies the result of the matrix opeartion from the Cloud application
# for the calculation
# for the runtime

# Function that verifies the calculation of the addition using Numpy
def add_verification_result():
    
    # Retrieving the matrices from a s3 bucket
    X = get_csv("cran-matrices-bucket", 'X.csv')
    Y = get_csv("cran-matrices-bucket", 'Y.csv')
    Z = get_csv("cran-matrices-bucket", 'Z.csv')
    
    # Addition
    result = X + Y
    
    # Comparison of results
    if Z.all() == result.all():
        print('The result of the addition is valid !')
        print(X)
        print('+')
        print(Y)
        print('=')
        print(Z)
    else:
        print('The result of the addition is not valid !')


# Function that verifies the calculation of the multiplication using Numpy
def mult_verification_result():
    
    # Retrieving the matrices from a s3 bucket
    X = get_csv("cran-matrices-bucket", 'X.csv')
    Y = get_csv("cran-matrices-bucket", 'Y.csv')
    Z = get_csv("cran-matrices-bucket", 'Z.csv')
    
    # Multiplication
    result = X @ Y
    
    # Comparison of results
    if Z.all() == result.all():
        print('The result of the multiplication is valid !')
        print(X)
        print('x')
        print(Y)
        print('=')
        print(Z)
    else:
        print('The result of the multiplication is not valid !')

# Function that calculates the time it takes to do the addition with for loops
def add_verification_time():
    
    # Retrieving the matrices from a s3 bucket
    X = get_csv("cran-matrices-bucket", 'X.csv')
    Y = get_csv("cran-matrices-bucket", 'Y.csv')
    
    # Creation of the output matrix
    C = np.zeros(X.shape)
    
    # Start time
    start = time.time()
    for i in range(len(X)):
        for j in range(len(X[0])):
            C[i][j] = X[i][j] + Y[i][j]
    end = time.time()
    
    # Calculate the time
    runtime = end-start
    runtime = round(runtime, 2)
    
    print('It takes ', runtime, 'sec to calculate manually the matrix addition')
    

# Function that calculates the time it takes to do the multiplication with for loops
def mult_verification_time():
    
    # Retrieving the matrices from a s3 bucket
    X = get_csv("cran-matrices-bucket", 'X.csv')
    Y = get_csv("cran-matrices-bucket", 'Y.csv')
    
    # Creation of the output matrix
    C = np.zeros((len(X),len(Y[0])))
    
    # Start time
    start = time.time()
    for i in range(len(X)):
        for j in range(len(Y[0])):
            c = 0
            for k in range(len(X[0])):
                c += X[i][k] * Y[k][j]
            
            C[i][j] = c
        
    end = time.time()
    
    # Calculate the time
    runtime = end-start
    runtime = round(runtime, 2)
    
    print('It takes ', runtime, 'sec to calculate manually the matrix multiplication')

In [22]:
# a function group that retrieves previous results that the user wants to display
# for the addition and the multiplication

# First function displays the folders present in the 'cran-inferences-bucket' s3 bucket
# and asks the user to choose between those folders
def inferences_0():
    
    # boto3 client
    s3 = boto3.client('s3')
    
    # bucket name
    bucket_name = 'cran-inferences-bucket'
    
    # parameters to retrieve the folders
    prefix = ""
    delimiter = "/"
    max_keys = 1000
    
    response = s3.list_objects_v2(Bucket=bucket_name, Prefix=prefix, Delimiter=delimiter, MaxKeys=max_keys)
    folders = response["CommonPrefixes"]
    
    print('To get inferences from addition or from multiplication, please choose between these two folders:')
    
    # List of folders
    for fol in folders:
        print(fol['Prefix'])
    
    input_user = input('Write ("Addition/") or ("Multiplication/"): ')
    print('\n')
    return input_user


# Second function checks if the user's input is either 'Addition/' or 'Multiplication/'
# and if not, calling again the first function
def inferences_1():
    
    # Calling the first function
    prefix = inferences_0()
    
    # While loop to check if the user's input is either 'Addition/' or 'Multiplication/'
    while True:
        
        if prefix == 'Addition/':
            break
            
        elif prefix == 'Multiplication/':
            break
        
        else:
            prefix = inferences_0() 
    
    return prefix


# Third function displays the subfolders present in the 'cran-inferences-bucket' s3 bucket
# and asks the user to choose between those folders
def inferences_2():
    
    # boto3 client
    s3 = boto3.client('s3')
    
    # bucket name
    bucket_name = 'cran-inferences-bucket'
    
    # parameters to retrieve the folders
    prefix = inferences_1()
    delimiter = "/"
    max_keys = 1000

    response = s3.list_objects_v2(Bucket=bucket_name, Prefix=prefix, Delimiter=delimiter, MaxKeys=max_keys)
    folders = response["CommonPrefixes"]
    
    print('To get the inferences, please choose between these files on the size of the matrices :')
    
    list_folders = []
    
    # List of folders
    for fol in folders:
        print(fol['Prefix'].replace(prefix,""))
        list_folders.append(fol['Prefix'].replace(prefix,""))
    
    input_user = input('Write one of those folders: ')
    print('\n')
    return prefix, list_folders, input_user


# Fourth function checks if the user's input is a subfolder inside the previous folder selected
# and if not, calling again the third function
def inferences_3():
    
    # Calling the third function
    prefix, list_folders, folder = inferences_2()
    
    # While loop to check if the user's input is a subfolder inside the previous folder selected
    while True:
        
        if folder in list_folders:
            break
            
        else:
            prefix, list_folders, folder = inferences_2()
    
    return prefix, folder

# Main function that retreives the csv files in the subfolder specified and displays them into numpy array
def main_inferences():
    
    # boto3 client
    s3 = boto3.client('s3')
    
    # bucket name
    bucket_name = 'cran-inferences-bucket'
    
    # Calling the fourth function
    folder_1, folder_2 = inferences_3()
    
    # parameters to retrieve the folders
    prefix = folder_1 + folder_2
    delimiter = "/"
    max_keys = 1000

    response = s3.list_objects_v2(Bucket=bucket_name, Prefix=prefix, Delimiter=delimiter, MaxKeys=max_keys)
    files = response["Contents"]
    
    # List with the csv files
    csv_files = [f["Key"] for f in files if f["Key"].endswith(".csv")]
    
    # Displaying them
    for file in csv_files:
        print(file.replace(prefix,""))
        print(get_csv(bucket_name, file))
        print('\n')

In [28]:
# Main function that asks the user to choose between calculating an addition and a multiplication
# Then remotly executes the correct python file on the EC2 Master using a SSH Client from Paramiko
# Displays the outputs
# After that, checks the results (correct calculation and runtime) 
def main():
    
    # boto3 client
    sqs_client = boto3.client("sqs")
    ec2_client = boto3.client("ec2")
    ssm_client = boto3.client("ssm")
    cloudwatch_client = boto3.client('cloudwatch')
    
    # Getting instance information
    describeInstance = ec2_client.describe_instances()

    PublicIp = []
    # We store the ip address from our master instance
    for i in describeInstance["Reservations"]:
        for instance in i["Instances"]:
            if instance["State"]["Name"] == "running":
                if re.search("^master", instance['Tags'][0]["Value"]):
                    PublicIp.append(instance["PublicIpAddress"])
    
    # Asking which opeartion the user wants to perform
    operation = ask_operation_2()

    if int(operation) == 0:
        
        # Asking the shape for the input matrices
        size_x, size_y = ask_shape_add_matrix_2()
        
        # Timeout initialization
        timeout = 160
        
        # Start the remotly run using the library 'threading'
        t = threading.Thread(target=run_addition, args=(labsuser_path, PublicIp[0], size_x, size_y, timeout))
        t.start()
        while t.is_alive():
            time.sleep(3)
         
        # Checking the result
        add_verification_result()
        print('\n')
        
        # Checking the time
        add_verification_time()
    
    elif int(operation) == 1:
        
        # Asking the shapes for the input matrices
        size_x, size_y = ask_shape_mult_matrix_1()
        x_0, x_1 = size_x[0], size_x[1]
        y_0, y_1 = size_y[0], size_y[1]
        
        # Timeout initialization
        timeout = 160
        
        # Start the remotly run using the library 'threading'
        t = threading.Thread(target=run_multiplication, args=(labsuser_path, PublicIp[0], x_0, x_1, y_0, y_1, timeout))
        t.start()
        while t.is_alive():
            time.sleep(3)
        
        # Checking the result
        mult_verification_result()
        print('\n')
        
        # Checking the time
        mult_verification_time()

## Delete Cloud Environment

In [29]:
# a function group that deletes everything we created for the Cloud environment

# Function that deletes every ec2 instances
def delete_ec2_instances():
    
    # boto3 client
    ec2 = boto3.resource('ec2')
    ec2_client = boto3.client("ec2")

    # Getting instance information
    describeInstance = ec2_client.describe_instances()

    InstancesId = []
    # We store the id from our instances
    for i in describeInstance["Reservations"]:
        for instance in i["Instances"]:
            if instance["State"]["Name"] == "running":
                InstancesId.append(instance["InstanceId"])
    
    # We terminate them
    ec2.instances.filter(InstanceIds = InstancesId).terminate()
    
    while True:
        response = ec2_client.describe_instance_status(InstanceIds=InstancesId, IncludeAllInstances=True)
        state = response['InstanceStatuses'][0]['InstanceState']

        # If status is 48 ('terminated'), then proceed, else wait 5 seconds and try again
        if state['Code'] == 48:
            break
        else:
            time.sleep(5)
    print('Instances Terminated')
    time.sleep(5)


# Function that deletes the security group we created
def delete_ec2_security_group():
    
    # To be sure, we did terminate all EC2 instances
    delete_ec2_instances()
    
    # boto3 client
    ec2 = boto3.client('ec2')
    
    # Get our VPC ID
    response = ec2.describe_security_groups()
    for sg in response['SecurityGroups']:
        if re.search("^ec2", sg['GroupName']): 
            security_group_id = sg['GroupId']
            
    # Delete our Security Group
    response = ec2.delete_security_group(GroupId=security_group_id)
    print('Security Group Deleted')


# Function that deletes the s3 bucket we created
def delete_s3_bucket():
    
    # boto3 client/ressource
    s3 = boto3.resource('s3')
    s3_client = boto3.client('s3')
    
    # Get the s3 bucket we created
    my_bucket = s3.Bucket('cran-matrices-bucket')
    
    # Delete every files in it
    for file in my_bucket.objects.all():
        s3.Object('cran-matrices-bucket', file.key).delete()
    
    # Delete the s3 bucket
    my_bucket.delete()
    
    print('Bucket Deleted')

# Function that deletes the sqs queues we created
def delete_sqs_queue():
    
    # boto3 client/ressource
    sqs = boto3.resource('sqs')
    sqs_client = boto3.client('sqs')
    
    # Get all our sqs queues
    queue_iter = sqs.queues.all()
    for queue in list(queue_iter):
        print(queue.url)
        
        # Delete them
        response = sqs_client.delete_queue(QueueUrl=queue.url)
        print('Queue Deleted')

In [25]:
# Main function that deletes our Cloud environment
def delete_cloud_env():
    
    # We display a loading bar with tqdm to monitor the progress of the distruction
    with tqdm(total=4) as pbar:
        
        # Delete the ec2 instances
        delete_ec2_instances()
        # We update the loading bar
        pbar.update(1)
        time.sleep(5)
        
        # Delete the security group
        delete_ec2_security_group()
        # We update the loading bar
        pbar.update(1)
        time.sleep(1)
        
        # Delete the s3 bucket
        delete_s3_bucket()
        # We update the loading bar
        pbar.update(1)
        time.sleep(1)
        
        # Delete the sqs queues
        delete_sqs_queue()
        # We update the loading bar
        pbar.update(1)
        time.sleep(1)

# Executions

## Create Cloud Environment 

In [26]:
# Deployement of the Cloud environment
create_cloud_env(local_aws_path, labsuser_path, 't3.large', 8, "cran-matrices-bucket", "request_queue_ec2", "response_queue_ec2")

  0%|                                                                                            | 0/6 [00:00<?, ?it/s]

Security Group Created sg-04502a0159581f885 in vpc vpc-031b9df76a3729a50.


 17%|██████████████                                                                      | 1/6 [00:02<00:12,  2.60s/it]

Master Instance Id:  i-01317ed7d36853cac
Start Master
Master is running !
Send aws folder & python files
Install packages
Done !


 33%|████████████████████████████                                                        | 2/6 [00:29<00:40, 10.00s/it]

Starting instance i-043a8ccb6f2461c9d
Starting instance i-0032b7c5afe641a81
Starting instance i-0fbab22451f2a16a1
Starting instance i-0b0e5f8353c6ceffb
Starting instance i-0e2d2163a167a24e9
Starting instance i-086a75689c5436baa
Starting instance i-01fce9fd1fed341f5
Starting instance i-0b8a83c305dc90230
Every workers are running !
Instance:  ec2.Instance(id='i-043a8ccb6f2461c9d')
Send aws folder & python files
Instance:  ec2.Instance(id='i-0032b7c5afe641a81')
Send aws folder & python files
Instance:  ec2.Instance(id='i-0fbab22451f2a16a1')
Send aws folder & python files
Instance:  ec2.Instance(id='i-0b0e5f8353c6ceffb')
Send aws folder & python files
Instance:  ec2.Instance(id='i-0e2d2163a167a24e9')
Send aws folder & python files
Instance:  ec2.Instance(id='i-086a75689c5436baa')
Send aws folder & python files
Instance:  ec2.Instance(id='i-01fce9fd1fed341f5')
Send aws folder & python files
Instance:  ec2.Instance(id='i-0b8a83c305dc90230')
Send aws folder & python files
Install packages
Don

 50%|██████████████████████████████████████████                                          | 3/6 [02:27<02:06, 42.22s/it]

Bucket S3 created !


 67%|████████████████████████████████████████████████████████                            | 4/6 [02:29<01:00, 30.09s/it]

SQS Queue  request_queue_ec2  created !


 83%|██████████████████████████████████████████████████████████████████████              | 5/6 [02:30<00:21, 21.61s/it]

SQS Queue  response_queue_ec2  created !


100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [02:32<00:00, 25.40s/it]


## Calculations 

In [30]:
# If you want to make calculation
main()

If you want to make an addition, please type 0
Or if you want to make a multiplication, please type 1
Choose: 1
Enter matrix shape (like "10 10" for (10,10) matrix): 500 500
Enter matrix shape (like "10 10" for (10,10) matrix): 500 500
We can calculate matrix multiplication for this shapes of matrices !
Each message will contain  86  rows from X and  86  columns from Y

So, to make the addition between X and Y, we need  8  workers

  0%|                                                    | 0/36 [00:00<?, ?it/s]
                                                                                
Sending Messages: 
100%|███████████████████████████████████████████| 36/36 [00:03<00:00, 11.31it/s]
Total number of message send:  36

  0%|                                                    | 0/36 [00:00<?, ?it/s]
                                                                                
Receiving Messages: 
100%|███████████████████████████████████████████| 36/36 [00:01<00:00, 24.22it/s]

It

In [31]:
# If you want to see previous calculations
main_inferences()

To get inferences from addition or from multiplication, please choose between these two folders:
Addition/
Multiplication/
Write ("Addition/") or ("Multiplication/"): Addition/


To get the inferences, please choose between these files on the size of the matrices :
10000/
15000/
5000/
Write one of those folders: 5000/


X_addition_5000.csv
[[0 3 4 ... 9 3 3]
 [8 1 3 ... 4 7 2]
 [8 5 3 ... 9 3 3]
 ...
 [7 4 4 ... 8 3 8]
 [2 8 4 ... 8 0 3]
 [0 3 2 ... 0 8 7]]


Y_addition_5000.csv
[[4 7 6 ... 3 7 2]
 [3 8 6 ... 7 3 8]
 [3 6 0 ... 6 9 7]
 ...
 [9 3 6 ... 8 9 1]
 [9 4 6 ... 4 8 0]
 [5 7 2 ... 4 7 9]]


Z_addition_5000.csv
[[ 4. 10. 10. ... 12. 10.  5.]
 [11.  9.  9. ... 11. 10. 10.]
 [11. 11.  3. ... 15. 12. 10.]
 ...
 [16.  7. 10. ... 16. 12.  9.]
 [11. 12. 10. ... 12.  8.  3.]
 [ 5. 10.  4. ...  4. 15. 16.]]




## Delete Cloud Environment

In [32]:
# Destruction of the Cloud envionment
delete_cloud_env()

  0%|                                                                                            | 0/4 [00:00<?, ?it/s]

Instances Terminated


 25%|█████████████████████                                                               | 1/4 [00:48<02:26, 48.84s/it]

Instances Terminated


 50%|██████████████████████████████████████████                                          | 2/4 [01:01<01:16, 38.04s/it]

Security Group Deleted


 75%|███████████████████████████████████████████████████████████████                     | 3/4 [01:03<00:27, 27.25s/it]

Bucket Deleted
https://sqs.us-east-1.amazonaws.com/607619944477/request_queue_ec2
Queue Deleted
https://sqs.us-east-1.amazonaws.com/607619944477/response_queue_ec2
Queue Deleted


100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:06<00:00, 16.73s/it]
